/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gesa Rizky Nugraha
 */
public class Framepanjang extends javax.swing.JFrame {

    /**
     * Creates new form Framepanjang
     */
    public Framepanjang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        cmb_menu = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        outinch = new javax.swing.JTextField();
        outkaki = new javax.swing.JTextField();
        outyard = new javax.swing.JTextField();
        outmeter = new javax.swing.JTextField();
        outcenti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KALKULATOR KONVERSI SATUAN PANJANG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Inch, Kaki, Yard, Meter dan Cm (Isikan satuan awal, pilih dari satuan)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Satuan Awal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Satuan Dari");

        cmb_menu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih:", "Inch", "Kaki (Feet/Foot)", "Yard", "M", "Cm" }));
        cmb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_menuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kesatuan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Inch");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kaki (Feet/Foot)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Yard");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Meter");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Centimeter");

        outinch.setEditable(false);

        outkaki.setEditable(false);

        outyard.setEditable(false);

        outmeter.setEditable(false);

        outcenti.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input)
                                    .addComponent(outinch)
                                    .addComponent(cmb_menu, 0, 143, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outmeter, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outyard, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outkaki)
                                    .addComponent(outcenti))
                                .addGap(106, 106, 106)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(outinch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(outkaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(outyard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(outmeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(outcenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_menuActionPerformed
        // TODO add your handling code here:
        String teksinput = input.getText();
        double input = Double.parseDouble(teksinput); 
        if(cmb_menu.getSelectedIndex()==0)
        {
            outinch.setText(null);
            outkaki.setText(null);
            outyard.setText(null);
            outmeter.setText(null);
            outcenti.setText(null);
        }
        if(cmb_menu.getSelectedIndex()==1)
        {
        double hasilinch = input * 1;
        String outputinch = String.valueOf(hasilinch);
        outinch.setText(outputinch);
        double hasilkaki = input * 0.0834;
        String outputkaki = String.valueOf(hasilkaki);
        outkaki.setText(outputkaki);
        double hasilyard = input * 0.0278;
        String outputyard = String.valueOf(hasilyard);
        outyard.setText(outputyard);
        double hasilmeter = input * 0.0254;
        String outputmeter = String.valueOf(hasilmeter);
        outmeter.setText(outputmeter);
        double hasilcenti = input * 2.54;
        String outputcenti = String.valueOf(hasilcenti);
        outcenti.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==2)
        {
        double hasilinch = input * 12;
        String outputinch = String.valueOf(hasilinch);
        outinch.setText(outputinch);
        double hasilkaki = input * 1;
        String outputkaki = String.valueOf(hasilkaki);
        outkaki.setText(outputkaki);
        double hasilyard = input * 0.34;
        String outputyard = String.valueOf(hasilyard);
        outyard.setText(outputyard);
        double hasilmeter = input * 0.3048;
        String outputmeter = String.valueOf(hasilmeter);
        outmeter.setText(outputmeter);
        double hasilcenti = input * 30.48;
        String outputcenti = String.valueOf(hasilcenti);
        outcenti.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==3)
        {
        double hasilinch = input * 36;
        String outputinch = String.valueOf(hasilinch);
        outinch.setText(outputinch);
        double hasilkaki = input * 3;
        String outputkaki = String.valueOf(hasilkaki);
        outkaki.setText(outputkaki);
        double hasilyard = input * 1;
        String outputyard = String.valueOf(hasilyard);
        outyard.setText(outputyard);
        double hasilmeter = input * 0.9144;
        String outputmeter = String.valueOf(hasilmeter);
        outmeter.setText(outputmeter);
        double hasilcenti = input * 91.44;
        String outputcenti = String.valueOf(hasilcenti);
        outcenti.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==4)
        {
        double hasilinch = input * 39.37;
        String outputinch = String.valueOf(hasilinch);
        outinch.setText(outputinch);
        double hasilkaki = input * 3.280;
        String outputkaki = String.valueOf(hasilkaki);
        outkaki.setText(outputkaki);
        double hasilyard = input * 1.09;
        String outputyard = String.valueOf(hasilyard);
        outyard.setText(outputyard);
        double hasilmeter = input * 1;
        String outputmeter = String.valueOf(hasilmeter);
        outmeter.setText(outputmeter);
        double hasilcenti = input * 100;
        String outputcenti = String.valueOf(hasilcenti);
        outcenti.setText(outputcenti);
        }
        if(cmb_menu.getSelectedIndex()==5)
        {
        double hasilinch = input * 0.3937;
        String outputinch = String.valueOf(hasilinch);
        outinch.setText(outputinch);
        double hasilkaki = input * 0.03280;
        String outputkaki = String.valueOf(hasilkaki);
        outkaki.setText(outputkaki);
        double hasilyard = input * 0.0109;
        String outputyard = String.valueOf(hasilyard);
        outyard.setText(outputyard);
        double hasilmeter = input * 0.01;
        String outputmeter = String.valueOf(hasilmeter);
        outmeter.setText(outputmeter);
        double hasilcenti = input * 1;
        String outputcenti = String.valueOf(hasilcenti);
        outcenti.setText(outputcenti);
        }
        
    }//GEN-LAST:event_cmb_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framepanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framepanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framepanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framepanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framepanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_menu;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField outcenti;
    private javax.swing.JTextField outinch;
    private javax.swing.JTextField outkaki;
    private javax.swing.JTextField outmeter;
    private javax.swing.JTextField outyard;
    // End of variables declaration//GEN-END:variables
}
